### ISSUE TITLE
Tab-expanding dash-separated properties

### ISSUE THREAD

**Issue by chriscoyier** [emmetio/codemirror-plugin#16]
If you TAB after a fully-written CSS property, it has weird effects:

```css
body {
  background-color[CURSOR]
}
```

Then press tab, you get:

```css
body {
  background: color;
}
```

Which is pretty weird, you'd think it would either do nothing since it's already expanded, or give you the more complete syntax like:

```css
body {
  background-color: #fff;
}
```
